name: Build VectorStore and Deploy to Vercel

on:
  # Optional to trigger from GitHub UI
  workflow_dispatch:
  # Trigger on branch push
  push:
    branches:
      - dev
    paths:
      - api/data.txt
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cone with PAT
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          git config --global user.email yashashm.dev@gmail.com
          git config --global user.name yashas-hm
          git checkout main

      - name: Fetch all branches
        run: |
          cd repo
          git fetch --all

      - name: Merge to production
        run: |
          cd repo
          git checkout production
          git merge main

      - name: Push to production with PAT
        run:  |
          cd repo
          git push --set-upstream origin production