name: Build VectorStore and Deploy to Vercel

on:
  # Optional to trigger from GitHub UI
  workflow_dispatch:
  # Trigger on branch push
  push:
    branches:
      - main
    paths:
      - api/data.txt
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Cone with PAT
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git .
          git config --global user.email yashashm.dev@gmail.com
          git config --global user.name yashas-hm
          git checkout main

      - name: Fetch all branches
        run: git fetch --all
          
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Merge to production
        run: |
          git checkout production
          git merge main
          
      - name: Generate Vectorstore
        run: |
          rm -rf ./vectorstore
          python vectorestore_generator.py

      - name: Push to production with PAT
        run:  |
          git push --set-upstream origin production