name: Deploy to Render

on:
  # Optional to trigger from GitHub UI
  workflow_dispatch:
  # Trigger on branch push
  push:
    branches:
      - main
    paths:
      - api/**
      - .vercelignore
      - app.py
      - requirements.txt
      - vectorestore_generator.py
      - vercel.json
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone with PAT
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git .
          git config --global user.email yashashm.dev@gmail.com
          git config --global user.name yashas-hm
          git checkout main
          
      - name: Fetch all branches
        run: git fetch --all

      - name: Merge to production
        run: |
          git checkout production
          git merge main

      - name: Push to production with PAT
        run: git push --set-upstream origin production