#name: Deploy to Vercel
#
#on:
#  push:
#    branches:
#      - main
#    paths:
#      - api/**
#      - .vercelignore
#      - app.py
#      - requirements.txt
#      - vectorestore_generator.py
#      - vercel.json
#    