name: Deploy to Render

on:
  # Optional to trigger from GitHub UI
  workflow_dispatch:
  # Trigger on branch push
  push:
    branches:
      - main
    paths:
      - api/**
      - .vercelignore
      - app.py
      - requirements.txt
      - vectorestore_generator.py
      - vercel.json
    
jobs:
  
  check-data-change:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Data File Check
        run: |
          FILE_TO_CHECK="api/data.txt"
          if git diff --name-only $GITHUB_SHA^..$GITHUB_SHA | grep -q "$FILE_TO_CHECK"; then
              echo "Data File has been modified. Cancelling workflow."
              exit 0
          else
              echo "Data File has not been modified."
          fi
      
  deploy:
    needs: check-data-change
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      
      - name: Git Configuration
        run: |
          git config --global user.email yashashm.dev@gmail.com
          git config --global user.name yashas-hm
          
      - name: Fetch all branches
        run: git fetch --all
          
      - name: Merge to production
        run: |
          git checkout production
          git merge main
      
      - name: Push to production with PAT
        run: |
          git remote remove origin
          git remote add origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git remote -v
          git push origin production